example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json 
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import wishlist_ajax


app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),  
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/',wishlist_ajax, name='wishlist_ajax')      
      
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from wishlist.models import BarangWishlist
from django import forms
class wishlist_form(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields =('nama_barang', 'harga_barang','deskripsi')

        widgets = {
            'nama_barang': forms.TextInput(attrs={'class':'form-control', 'placeholder':'masukkan judul'}),
            'harga_barang': forms.TextInput(attrs={'class':'form-control', 'placeholder':'masukkan deskripsi'}),
            'deskripsi': forms.TextInput(attrs={'class':'form-control', 'placeholder':'masukkan judul'}),
        }

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from wishlist.forms import wishlist_form



@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Debby Trinita',
    'last_login' : request.COOKIES['last_login'],
    
}
    return (render(request, "wishlist.html",context))

def show_xml(request):
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

data = BarangWishlist.objects.all()
data_barang_wishlist = BarangWishlist.objects.all()


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')

    context = {}
    return render(request, 'login.html', context)

    

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def wishlist_ajax(request):
    context={
        'last_login' : request.COOKIES['last_login'],
    }
    return(render (request, "wishlist_ajax.html",context))

def add_new_wishlist(request):
    if request.method == "POST":
        form = wishlist_form(request.POST)
        if form.is_valid():
            nama_barang_user = request.POST.get('nama_barang')
            harga_barang_user = request.POST.get('harga_barang')
            deskripsi_user = request.POST.get('deskripsi')
            new_wishlist = BarangWishlist(nama_barang=nama_barang_user,harga_barang=harga_barang_user,description=deskripsi_user)
            new_wishlist.save()
           
            return HttpResponseRedirect(reverse('wishlist:wishlist_ajax'))

    context ={
            'form': wishlist_form
    }
    return render(request, 'wishlist_ajax.html', context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>

</html>
{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Debby Trinita</a>
    <button><a class="btn btn-secondary" href="{% url 'wishlist:logout' %}">Logout</a></button>
  </div>
</nav>
<br>
<table class="table table-striped table-hover">
    <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    
    {% for barang in list_barang %}
        <tr>
            <td>{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
    
{% endfor %}


</table>

<br><br><br>
<h6>Sesi terakhir login: {{ last_login }}</h6>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <style>
    .container{
      width: 30%;
    }
  </style>
  </head>


</html>
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<script>
  $(document).ready(function () {

      // FETCHING DATA FROM JSON FILE
      $.getJSON("{% url 'wishlist:show_json' %}", 
              function (data) {
          var barang = '';

          // ITERATING THROUGH OBJECTS
          $.each(data, function (key, value) {

              //CONSTRUCTION OF ROWS HAVING
              // DATA FROM JSON OBJECT
              barang += '<tr>';
              barang += '<td>' + 
                  value.fields.nama_barang + '</td>';

              barang += '<td>' + 
                  value.fields.harga_barang + '</td>';

              barang += '<td>' + 
                  value.fields.deskripsi + '</td>';


              barang += '</tr>';
          });
            
          //INSERTING ROWS INTO TABLE 
          $(".btn-add").submit(function () {
                tableBody = $("table tbody");
                tableBody.append(barang);
            });
          $('#table').append(barang);
          
      });
  });
</script>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Debby Trinita</a>
    <form action="{% url 'wishlist:logout' %}" method="post" >
      {% csrf_token %}
      <button type="submit" class="btn btn-secondary navbar-btn">Logout</button>
  </form>
  </div>
</nav>
<br>
<table class="table table-striped table-hover" id="table">
    <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    
    {% for barang in list_barang %}
        <tr>
            <td>{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
    
{% endfor %}


</table>

<form method="POST" action="" class="container" >
    <h3 class="text-center">Tambah Wishlist</h3>
    {% csrf_token %}
    <div class="form-group">
      <label>Nama Barang</label>
      <input type="text" name="nama_barang" placeholder="Masukkan nama barang" class="form-control" required>
    </div>
    <div class ="form-group">
      <label>Harga Barang</label>
      <input type="text" name="harga_barang" placeholder="Masukkan harga barang" class="form-control" required>
    </div>
    <div class ="form-group">
      <label>Deskripsi</label>
      <input type="text" name="deskripsi" placeholder="Masukkan deskripsi" class="form-control" required>
    </div>
    <div class="d-grid gap-2 mt-2">
      <button type="submit" class="btn btn-secondary btn-sm" value="add" id="btn-add">SUBMIT</button>
    </div>
    
</form>


<br><br><br>
<h6>Sesi terakhir login: {{ last_login }}</h6>


{% endblock content %}